### ISSUE TITLE
Dead/inaccessible link

### ISSUE THREAD

**Issue by atchoo78** [telldus/tellstick-server-plugins#1]
@mickeprag : 

At https://github.com/telldus/tellstick-server-plugins/blob/master/http/long_description.md you write:
> More examples can be found here:
> https://github.com/telldus/tellstick-lua-examples/tree/master/plugins/http
> 

But when I click the link:
![screen shot 2017-05-06 kl 07 38 33](https://cloud.githubusercontent.com/assets/20549049/25770234/8e2c69ea-3230-11e7-9c30-62900b32137c.png)

I don't know if this is a member access issue or not, but now you know anyway. 💡

Andreas

**Comment by mickeprag** [comment]
The exampes has not yet been pushed since the http plugin currently crashes the server. There is a segfault that need fixing first:
https://github.com/scoder/lupa/issues/84
