### ISSUE TITLE
Mailsender local plugin broken

### ISSUE THREAD

**Issue by jensah** [telldus/tellstick-server-plugins#11]
port = ConfigurationString(
		defaultValue='25',
		title='SMTP server port',
		minLength=4
Due to minLenght 4 and default val 2 it breaks and won't work. Remove minLength=4 or atleast change to =2

**Comment by edvarddrake** [comment]
Furthermore, the minLength= 4 seems to translate into browser side validation against the pattern ".{4,0}", which generates an error, and probably fails completely. This means that the minLength=4 for smtpServer causes problems, too. 

Removing both these constraints from the plugin probably solves the urgent problem (which makes the plugin completely useless). The way minLength is converted into validation pattern may be in the plugin mechanism, and probably needs a change too. But as a minimum solution, just bypassing it by not providing minLength may be simpler and quicker.

**Comment by mickeprag** [comment]
The correct fix must to be using ConfigurationNumber instead of ConfigurationString?

Fixed in fab725c60cb1a4a8d0adc4e599da8d4c6d989c65
