### ISSUE TITLE
How to install plugin to device?

### ISSUE THREAD

**Issue by jonathanazulay** [telldus/tellstick-server-plugins#2]
I have a Tellstick net v2 and want to try the philips hue plugin. But how do I install it? Can't seem to find any instructions anywhere.

**Comment by mickeprag** [comment]
This is not a support forum. Please contact support instead.

**Comment by jonathanazulay** [comment]
@mickeprag But perhaps something could be added to the readme? Feels like I'm missing something. The link in the readme does not say how to upload the zip to the device.
