### ISSUE TITLE
No way of installing a self-made plugin

### ISSUE THREAD

**Issue by xeor** [telldus/tellstick-server-plugins#6]
It looks like much of the code is ready... But even tho you make a plugin you want to use, there is no way for me to use my own key.

When will the `return {'success': False, 'msg': 'Importing of custom keys are not allowed'}` block be removed?

Importing keys are not possible... https://github.com/telldus/tellstick-server/blob/master/plugin-loader/src/pluginloader/Loader.py#L190

**Comment by mickeprag** [comment]
Please contact the support and they will manually add your key to your device.
For local development, please just comment this line.
