### ISSUE TITLE
Please update link to docs

### ISSUE THREAD

**Issue by atchoo78** [telldus/tellstick-server-plugins#8]
Hello,

The current link to the latest plugins docs is:
https://tellstick-server.readthedocs.io/en/latest/python.html

Which returns the big ol' 404. 

If I'm not mistaken, it should be:

https://tellstick-server.readthedocs.io/en/latest/python/
or
https://tellstick-server.readthedocs.io/en/latest/python/intro.html 

Thanks,

Andreas

**Comment by mickeprag** [comment]
Thanks
